-- CRM Template Supabase schema
-- Run this in the Supabase SQL editor.

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  status text default 'Lead',
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  scope_of_work text default '',
  job_cost numeric default 0,
  created_at timestamptz not null default now()
);

-- Run these if upgrading an existing database:
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS scope_of_work text DEFAULT '';
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS job_cost numeric DEFAULT 0;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  amount numeric not null default 0,
  payment_date timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_overrides (
  year int primary key,
  total_expected numeric default 0,
  total_received numeric default 0,
  total_remaining numeric default 0,
  total_clients int default 0,
  notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  title text default 'New Job',
  status text default 'Prospect',
  scope_of_work text default '',
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  job_cost numeric default 0,
  created_at timestamptz not null default now()
);

create index if not exists jobs_client_id_idx on public.jobs (client_id);
create index if not exists jobs_created_at_idx on public.jobs (created_at desc);

-- Run this if upgrading an existing database:
-- CREATE TABLE IF NOT EXISTS public.jobs (id bigint generated by default as identity primary key, client_id bigint references public.clients(id) on delete cascade, title text default 'New Job', status text default 'Prospect', scope_of_work text default '', total_due numeric default 0, amount_paid numeric default 0, balance numeric default 0, job_cost numeric default 0, created_at timestamptz not null default now());

create table if not exists public.finance_margin_entries (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  client_name text default '',
  category text default 'Misc',
  project text default '',
  invoice_status text default 'Pending',
  amount numeric default 0,
  expense_type text default 'one-time',
  recurring boolean default false,
  expense_date timestamptz not null default now(),
  notes text default '',
  attachment_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clients_created_at_idx on public.clients (created_at desc);
create index if not exists payments_client_id_idx on public.payments (client_id);
create index if not exists payments_payment_date_idx on public.payments (payment_date desc);
create index if not exists notes_client_id_idx on public.notes (client_id);
create index if not exists notes_created_at_idx on public.notes (created_at desc);
create index if not exists finance_margin_entries_client_id_idx on public.finance_margin_entries (client_id);
create index if not exists finance_margin_entries_expense_date_idx on public.finance_margin_entries (expense_date desc);
create index if not exists finance_margin_entries_category_idx on public.finance_margin_entries (category);

-- Row Level Security is switched ON for every table at the END of this file
-- (see "SECURITY: Row Level Security"). Keep that block last so it also
-- covers tables added by later upgrade sections.

-- =============================================
-- Multi-tenant onboarding system tables
-- =============================================

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  tagline text not null default '',
  description text not null default '',
  contact_email text not null default '',
  logo_url text not null default '',
  brand_primary_color text not null default '#2563eb',
  brand_secondary_color text not null default '#2563eb',
  onboarding_step int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  display_name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  company_id uuid references public.companies(id) on delete set null,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_email_idx on public.users (email);
create index if not exists users_company_id_idx on public.users (company_id);
create index if not exists companies_slug_idx on public.companies (slug);

-- Prevent a second admin from being inserted within the same company.
-- Each company can have one admin row, but different companies may each have their own admin.
drop index if exists public.users_single_admin_idx;
create unique index if not exists users_single_admin_idx on public.users (company_id) where role = 'admin';

-- Migration: v2 onboarding step tracking
-- Run this if upgrading an existing database that already has the companies table:
-- ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS onboarding_step int NOT NULL DEFAULT 1;
-- UPDATE public.companies SET onboarding_step = 1 WHERE onboarding_step IS NULL;

-- =============================================
-- Feature selection for onboarding step 3
-- =============================================

create table if not exists public.company_components (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  component_type text not null,
  is_active boolean not null default true,
  display_order int not null default 0,
  config jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_components_company_id_idx on public.company_components (company_id);
create index if not exists company_components_company_order_idx on public.company_components (company_id, display_order);

-- Prevent duplicate component_type per company
create unique index if not exists company_components_unique_type_per_company
  on public.company_components (company_id, component_type);

-- =============================================
-- Client type tagging (Feature 6)
-- =============================================
-- Add client_type column if it doesn't already exist.
-- Uses DEFAULT 'one-off' so existing rows are backfilled automatically.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
  ) THEN
    ALTER TABLE public.clients ADD COLUMN client_type text NOT NULL DEFAULT 'one-off'
      CHECK (client_type IN ('one-off', 'recurring'));
  END IF;
END $$;

-- Force schema cache refresh so the new column is immediately visible.
-- PostgREST caches the schema; without this, you may see
-- "Could not find the 'client_type' column" errors.
NOTIFY pgrst, 'reload schema';

-- Verification: query the column to confirm it exists in the schema cache
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type';

SELECT * FROM public.clients LIMIT 0;

-- =============================================
-- Business workflow preference (Step 2)
-- =============================================
-- Add business_workflow column if it doesn't already exist.
-- Default is 'both' so existing companies continue to work.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN business_workflow text NOT NULL DEFAULT 'both'
      CHECK (business_workflow IN ('single', 'returning', 'both'));
  END IF;
END $$;

-- Force Supabase schema cache refresh so the new column is immediately visible.
-- Without this, the PostgREST API will return:
--   "Could not find the 'business_workflow' column"
-- This NOTIFY command invalidates the schema cache across all connections.
NOTIFY pgrst, 'reload schema';

-- Verification: confirm the column now exists and is visible in the schema cache.
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow';

-- Trigger a schema cache refresh by selecting from the table.
-- This ensures the column is recognized before any UPDATE/DELETE operations.
SELECT * FROM public.companies LIMIT 0;

-- =============================================
-- Admin claimed guard (registration enforcement)
-- =============================================
-- Track whether the first admin has registered.  Uses the existing
-- `settings` table (key/value store) so no new table is needed.
-- The server queries this flag to decide whether to redirect visitors
-- to /register or show the normal login page.
--
-- Seed row (insert if missing):
INSERT INTO public.settings (key, value)
SELECT 'admin_claimed', 'false'
WHERE NOT EXISTS (SELECT 1 FROM public.settings WHERE key = 'admin_claimed');

-- =============================================
-- Activity log (Feature: Activity Log)
-- =============================================
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_log_company_id_idx on public.activity_log (company_id);
create index if not exists activity_log_created_at_idx on public.activity_log (created_at desc);
create index if not exists activity_log_action_idx on public.activity_log (action);
create index if not exists activity_log_entity_type_idx on public.activity_log (entity_type);

-- =============================================
-- Email templates (Feature: Email Templates)
-- =============================================
create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  subject text not null,
  body text not null,
  type text not null default 'custom',
  variables jsonb default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_templates_company_id_idx on public.email_templates (company_id);

-- =============================================
-- Currency support (Feature: Multi-Currency)
-- =============================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'currency'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN currency text NOT NULL DEFAULT 'USD';
  END IF;
END $$;

-- =============================================
-- SCHEMA VERIFICATION
-- Run these SELECT statements to confirm all
-- columns and tables exist and are visible.
-- =============================================

-- Verify company_components table exists
SELECT EXISTS (
  SELECT FROM information_schema.tables
  WHERE table_schema = 'public' AND table_name = 'company_components'
) AS company_components_exists;

-- Verify business_workflow column exists on companies
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
) AS business_workflow_column_exists;

-- Verify client_type column exists on clients
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
) AS client_type_column_exists;

-- Verify admin_claimed seed row exists
SELECT EXISTS (
  SELECT 1 FROM public.settings WHERE key = 'admin_claimed'
) AS admin_claimed_seed_exists;

-- Verify users_single_admin_idx exists
SELECT EXISTS (
  SELECT 1 FROM pg_indexes
  WHERE indexname = 'users_single_admin_idx'
) AS single_admin_index_exists;

-- ======================================================
-- SERVICES PRESETS TABLE
-- ======================================================
CREATE TABLE IF NOT EXISTS public.services (
  id BIGSERIAL PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  description TEXT DEFAULT '',
  default_rate DECIMAL(10,2) DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ======================================================
-- CLIENT-SERVICE PIVOT TABLE (scope line items)
-- ======================================================
CREATE TABLE IF NOT EXISTS public.client_service (
  id BIGSERIAL PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  service_id BIGINT NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  custom_rate DECIMAL(10,2) DEFAULT NULL,
  notes TEXT DEFAULT '',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(client_id, service_id)
);

-- Force schema cache refresh (run these separately if columns still missing):
--   NOTIFY pgrst, 'reload schema';
-- Or select from each table to trigger cache refresh:
--   SELECT * FROM public.companies LIMIT 0;
--   SELECT * FROM public.clients LIMIT 0;
--   SELECT * FROM public.company_components LIMIT 0;

-- =============================================================
-- TEMPLATE UPGRADE: Google auth, per-user client access,
-- client pipeline stage, job tags, and estimate/invoice line
-- items with cost categories.
--
-- Everything below is purely ADDITIVE (new nullable columns,
-- new tables) or a narrow, documented value rename. Nothing here
-- drops a column, drops a table, or deletes a row. Safe to run
-- multiple times (all statements are IF NOT EXISTS / idempotent).
-- =============================================================

-- ---- USERS: support Google sign-in (Supabase Auth) ----------
-- password_hash is no longer required once a user signs in with
-- Google, so it is relaxed to nullable. Existing password-based
-- rows are untouched.
ALTER TABLE public.users ALTER COLUMN password_hash DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'auth_uid'
  ) THEN
    ALTER TABLE public.users ADD COLUMN auth_uid uuid UNIQUE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'picture_url'
  ) THEN
    ALTER TABLE public.users ADD COLUMN picture_url text NOT NULL DEFAULT '';
  END IF;
END $$;

-- ---- CLIENTS: per-user assignment + company scoping ----------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'assigned_user_id'
  ) THEN
    ALTER TABLE public.clients ADD COLUMN assigned_user_id uuid REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'company_id'
  ) THEN
    ALTER TABLE public.clients ADD COLUMN company_id uuid REFERENCES public.companies(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS clients_assigned_user_id_idx ON public.clients (assigned_user_id);
CREATE INDEX IF NOT EXISTS clients_company_id_idx ON public.clients (company_id);

-- ---- CLIENT STAGE: normalize to the 6-stage pipeline ----------
-- Client stage values going forward: Lead, Photo report, Prospect,
-- Approved, Invoiced, Closed. This is a client-level PIPELINE STAGE
-- only — it is intentionally separate from job.status (per-job
-- workflow) and job.tags (per-job free-form labels) below.
--
-- Existing rows are remapped 1:1, never deleted:
--   'Invoice'   -> 'Invoiced'  (straight rename, same meaning)
--   'Completed' -> 'Approved'  (closest still-active pipeline stage;
--                                'Completed' is not one of the six
--                                stages the client asked for)
-- All other existing values (Lead, Prospect, Approved, Closed) are
-- already valid and untouched.
UPDATE public.clients SET status = 'Invoiced' WHERE status = 'Invoice';
UPDATE public.clients SET status = 'Approved' WHERE status = 'Completed';

-- ---- JOBS: job-level tags (distinct from job.status workflow) --
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'jobs' AND column_name = 'tags'
  ) THEN
    ALTER TABLE public.jobs ADD COLUMN tags text[] NOT NULL DEFAULT '{}';
  END IF;
END $$;

-- ---- JOB LINE ITEMS: estimate/invoice cost breakdown -----------
-- One row per cost line on a job's estimate/invoice. category is
-- restricted to the six required cost types; existing jobs have no
-- rows here yet (they keep using the single job.total_due figure
-- until someone adds line items).
CREATE TABLE IF NOT EXISTS public.job_line_items (
  id BIGSERIAL PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  description TEXT NOT NULL DEFAULT '',
  quantity NUMERIC NOT NULL DEFAULT 1,
  unit_price NUMERIC NOT NULL DEFAULT 0,
  category TEXT NOT NULL DEFAULT 'Miscellaneous'
    CHECK (category IN ('Labor', 'Materials', 'Commissions', 'Meals/Drinks', 'Miscellaneous', 'Permits')),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_line_items_job_id_idx ON public.job_line_items (job_id);

-- Backfill safety net: if a future ALTER ever adds a category
-- column to an older line-items table with existing un-categorized
-- rows, default them to 'Miscellaneous' rather than guessing.
UPDATE public.job_line_items SET category = 'Miscellaneous' WHERE category IS NULL OR category = '';

-- ---- SESSION STORE (keeps logins alive across restarts) --------
-- Used by express-session via connect-pg-simple when SUPABASE_DATABASE_URL is
-- set (see the README). Without this table the app creates it on demand at
-- first use, so you normally do not need to run this section by hand.
-- Safe to re-run.
CREATE TABLE IF NOT EXISTS public.session (
  sid TEXT PRIMARY KEY,
  sess JSON NOT NULL,
  expire TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS session_expire_idx ON public.session (expire);

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v4: job-level notes, and a proper documents/photos
-- attachment system for jobs (separate from the older per-client PDF
-- upload feature, which is untouched and keeps working as-is).
--
-- Purely additive: a new nullable column and a new table. Nothing here
-- drops a column, drops a table, or deletes a row. Safe to run multiple
-- times.
-- =============================================================

-- ---- NOTES: optional job scoping ------------------------------
-- Existing notes stay client-only (job_id left null). A note created from
-- a job's own Notes section gets both job_id and its parent client_id set,
-- so it shows up on that job specifically rather than in the client-level
-- notes list.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'notes' AND column_name = 'job_id'
  ) THEN
    ALTER TABLE public.notes ADD COLUMN job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS notes_job_id_idx ON public.notes (job_id);

-- ---- JOB FILES: documents vs. photos, with real metadata -------
-- One row per uploaded file. `category` is what keeps Documents and
-- Photos visually and functionally separate on the job page — storage_path
-- is the exact object path in the configured storage backend (Supabase
-- Storage, or the local uploads/ folder in dev), so listing/downloading a
-- file never has to re-derive it from a filename convention.
CREATE TABLE IF NOT EXISTS public.job_files (
  id BIGSERIAL PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  category TEXT NOT NULL DEFAULT 'document' CHECK (category IN ('document', 'photo')),
  file_name TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type TEXT DEFAULT '',
  size_bytes BIGINT DEFAULT 0,
  uploaded_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_files_job_id_idx ON public.job_files (job_id);
CREATE INDEX IF NOT EXISTS job_files_category_idx ON public.job_files (job_id, category);

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v5: allow multiple admins per company.
--
-- Originally each company could only ever have one admin (enforced by
-- users_single_admin_idx, added in the v3 upgrade above). That is no
-- longer the desired behavior — an admin should be able to promote any
-- number of other users to admin from Settings — so the constraint is
-- dropped. Nothing else about the users table changes, and no rows are
-- affected: every existing admin simply keeps their role.
-- =============================================================
DROP INDEX IF EXISTS public.users_single_admin_idx;

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v6: client overview redesign.
--
-- The client page now shows a Technician next to the Salesperson, and job
-- payments are also written to the payments ledger (so Finance counts
-- them). This adds:
--   - clients.technician  — who does the work for the client (free text)
--   - payments.job_id     — which job a payment was recorded on, for per-job
--                           payment history. Existing payments keep job_id
--                           NULL (they were recorded on the client).
--
-- The app works without this section (technician names are kept in the
-- settings table until the column exists, and job payment history is simply
-- hidden). Running it is purely ADDITIVE: new nullable/defaulted columns and
-- an index. No table or column is dropped and no row is deleted. Safe to run
-- multiple times.
-- =============================================================
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS technician text NOT NULL DEFAULT '';

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS job_id bigint REFERENCES public.jobs(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS payments_job_id_idx ON public.payments (job_id);

-- Carry over technician names saved before the column existed (the app kept
-- them in settings as "client_technician:<client id>"). Only fills clients
-- whose technician is still empty; the settings rows are left in place.
UPDATE public.clients AS c
SET technician = s.value
FROM public.settings AS s
WHERE s.key = 'client_technician:' || c.id::text
  AND COALESCE(c.technician, '') = '';

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v7: custom job expense categories.
--
--   companies -> expense_categories -> job_expenses <- jobs
--
-- Each business manages its own expense categories (Settings -> Expense
-- Categories); each job can hold itemized costs, each with a category. A
-- job's cost (jobs.job_cost) is kept equal to the sum of its expenses by the
-- app, so profit, margin, client totals and Finance keep working unchanged.
--
-- Categories are referenced by id, so renaming one renames it on every
-- existing expense. A category that is in use can't be deleted (ON DELETE
-- RESTRICT) — the app deactivates it instead, which hides it from new
-- expenses and keeps every historical expense and total.
--
-- Purely ADDITIVE: two new tables, indexes, and four default categories per
-- existing business. Existing jobs keep their single job_cost figure until
-- someone itemizes them (the app then keeps that figure as an
-- "Uncategorized" expense). No table or column is dropped and no row is
-- deleted. Safe to run multiple times.
-- =============================================================
CREATE TABLE IF NOT EXISTS public.expense_categories (
  id BIGSERIAL PRIMARY KEY,
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS expense_categories_company_name_idx
  ON public.expense_categories (company_id, lower(name));

CREATE TABLE IF NOT EXISTS public.job_expenses (
  id BIGSERIAL PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.expense_categories(id) ON DELETE RESTRICT,
  description TEXT NOT NULL DEFAULT '',
  amount NUMERIC NOT NULL DEFAULT 0 CHECK (amount >= 0),
  expense_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_expenses_job_id_idx ON public.job_expenses (job_id);
CREATE INDEX IF NOT EXISTS job_expenses_category_id_idx ON public.job_expenses (category_id);

-- Default categories for every business that doesn't have any yet.
INSERT INTO public.expense_categories (company_id, name, sort_order)
SELECT c.id, d.name, d.sort_order
FROM public.companies AS c
CROSS JOIN (VALUES
  ('Labor', 0),
  ('Materials', 1),
  ('Commissions', 2),
  ('Miscellaneous Expenses', 3)
) AS d(name, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.expense_categories AS e WHERE e.company_id = c.id
);

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v9: job scheduling (the Calendar).
-- (v8 — customer tags — is on its own branch; the two are independent.)
--
-- A job's schedule is stored on the job itself, so the job stays the one
-- source of truth and nothing can drift out of sync:
--   jobs.scheduled_start  DATE  estimated start date
--   jobs.duration_days    INT   how many days the job takes (1-365)
-- The Calendar shows every Approved job that has both: a 3-day job starting
-- Oct 10 covers Oct 10-12. Changing the date, the duration or the status,
-- or deleting the job, changes the calendar straight away.
--
-- Purely ADDITIVE: two nullable columns and an index. Existing jobs simply
-- have no schedule. Nothing is changed, dropped or deleted. Safe to run
-- multiple times.
-- =============================================================
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS scheduled_start DATE;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS duration_days INT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'jobs_duration_days_check') THEN
    ALTER TABLE public.jobs ADD CONSTRAINT jobs_duration_days_check
      CHECK (duration_days IS NULL OR duration_days BETWEEN 1 AND 365);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS jobs_scheduled_start_idx
  ON public.jobs (scheduled_start) WHERE scheduled_start IS NOT NULL;

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- TEMPLATE UPGRADE v10: line-item pricing on estimates/invoices.
--
-- Some customers (often commercial) want the estimate/invoice to list each
-- service with its own price instead of one total. This stores that choice
-- per job:
--   jobs.show_line_item_prices  BOOLEAN  false = one total (the original
--                                        format), true = each service and
--                                        its price, then the total
-- It only changes what the document shows. The services (job_line_items)
-- stay the one source of prices, and the job total is still their sum.
--
-- Purely ADDITIVE: one column defaulting to false, so every existing job
-- keeps the one-total format. Nothing is changed, dropped or deleted. Safe
-- to run multiple times.
-- =============================================================
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS show_line_item_prices BOOLEAN NOT NULL DEFAULT false;

NOTIFY pgrst, 'reload schema';

-- =============================================================
-- SECURITY: Row Level Security on every table (keep this block LAST).
--
-- The browser receives the public (anon / publishable) key — it is shipped
-- on the login page by design. Any table without RLS can be read AND
-- written by anyone holding that key through Supabase's REST API.
--
-- This app never lets the browser touch tables: every read and write goes
-- through the server, which uses the secret / service-role key, and that key
-- bypasses RLS. So the safe setting is RLS ON with NO policies:
--   public key  -> no rows, no writes
--   the server  -> works exactly as before
-- Do not add policies for anon/authenticated to "make something work"; send
-- it through the server instead.
--
-- Safe to run multiple times. Verify after every deploy with:
--   node scripts/verify-security.js
-- =============================================================
DO $$
DECLARE
  t record;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND NOT rowsecurity LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tablename);
  END LOOP;
END $$;

NOTIFY pgrst, 'reload schema';
