-- CRM Template Supabase schema
-- Run this in the Supabase SQL editor.

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  status text default 'Lead',
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  amount numeric not null default 0,
  payment_date timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_overrides (
  year int primary key,
  total_expected numeric default 0,
  total_received numeric default 0,
  total_remaining numeric default 0,
  total_clients int default 0,
  notes text,
  updated_at timestamptz not null default now()
);

create index if not exists clients_created_at_idx on public.clients (created_at desc);
create index if not exists payments_client_id_idx on public.payments (client_id);
create index if not exists payments_payment_date_idx on public.payments (payment_date desc);
create index if not exists notes_client_id_idx on public.notes (client_id);
create index if not exists notes_created_at_idx on public.notes (created_at desc);

-- Optional: leave Row Level Security off if you want the server-side service role
-- to handle all access without policies.
