-- CRM Template Supabase schema
-- Run this in the Supabase SQL editor.

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text default '',
  email text default '',
  address text default '',
  status text default 'Lead',
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  scope_of_work text default '',
  job_cost numeric default 0,
  created_at timestamptz not null default now()
);

-- Run these if upgrading an existing database:
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS scope_of_work text DEFAULT '';
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS job_cost numeric DEFAULT 0;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  amount numeric not null default 0,
  payment_date timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_overrides (
  year int primary key,
  total_expected numeric default 0,
  total_received numeric default 0,
  total_remaining numeric default 0,
  total_clients int default 0,
  notes text,
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  title text default 'New Job',
  status text default 'Prospect',
  scope_of_work text default '',
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  job_cost numeric default 0,
  created_at timestamptz not null default now()
);

create index if not exists jobs_client_id_idx on public.jobs (client_id);
create index if not exists jobs_created_at_idx on public.jobs (created_at desc);

-- Run this if upgrading an existing database:
-- CREATE TABLE IF NOT EXISTS public.jobs (id bigint generated by default as identity primary key, client_id bigint references public.clients(id) on delete cascade, title text default 'New Job', status text default 'Prospect', scope_of_work text default '', total_due numeric default 0, amount_paid numeric default 0, balance numeric default 0, job_cost numeric default 0, created_at timestamptz not null default now());

create table if not exists public.finance_margin_entries (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  client_name text default '',
  category text default 'Misc',
  project text default '',
  invoice_status text default 'Pending',
  amount numeric default 0,
  expense_type text default 'one-time',
  recurring boolean default false,
  expense_date timestamptz not null default now(),
  notes text default '',
  attachment_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clients_created_at_idx on public.clients (created_at desc);
create index if not exists payments_client_id_idx on public.payments (client_id);
create index if not exists payments_payment_date_idx on public.payments (payment_date desc);
create index if not exists notes_client_id_idx on public.notes (client_id);
create index if not exists notes_created_at_idx on public.notes (created_at desc);
create index if not exists finance_margin_entries_client_id_idx on public.finance_margin_entries (client_id);
create index if not exists finance_margin_entries_expense_date_idx on public.finance_margin_entries (expense_date desc);
create index if not exists finance_margin_entries_category_idx on public.finance_margin_entries (category);

-- Optional: leave Row Level Security off if you want the server-side service role
-- to handle all access without policies.

-- =============================================
-- Multi-tenant onboarding system tables
-- =============================================

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  tagline text not null default '',
  description text not null default '',
  contact_email text not null default '',
  logo_url text not null default '',
  brand_primary_color text not null default '#2563eb',
  brand_secondary_color text not null default '#7c3aed',
  onboarding_step int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  display_name text not null default '',
  role text not null default 'user' check (role in ('admin', 'user')),
  company_id uuid references public.companies(id) on delete set null,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_email_idx on public.users (email);
create index if not exists users_company_id_idx on public.users (company_id);
create index if not exists companies_slug_idx on public.companies (slug);

-- Prevent a second admin from being inserted within the same company.
-- Each company can have one admin row, but different companies may each have their own admin.
drop index if exists public.users_single_admin_idx;
create unique index if not exists users_single_admin_idx on public.users (company_id) where role = 'admin';

-- Migration: v2 onboarding step tracking
-- Run this if upgrading an existing database that already has the companies table:
-- ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS onboarding_step int NOT NULL DEFAULT 1;
-- UPDATE public.companies SET onboarding_step = 1 WHERE onboarding_step IS NULL;

-- =============================================
-- Feature selection for onboarding step 3
-- =============================================

create table if not exists public.company_components (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  component_type text not null,
  is_active boolean not null default true,
  display_order int not null default 0,
  config jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists company_components_company_id_idx on public.company_components (company_id);
create index if not exists company_components_company_order_idx on public.company_components (company_id, display_order);

-- Prevent duplicate component_type per company
create unique index if not exists company_components_unique_type_per_company
  on public.company_components (company_id, component_type);

-- =============================================
-- Client type tagging (Feature 6)
-- =============================================
-- Add client_type column if it doesn't already exist.
-- Uses DEFAULT 'one-off' so existing rows are backfilled automatically.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
  ) THEN
    ALTER TABLE public.clients ADD COLUMN client_type text NOT NULL DEFAULT 'one-off'
      CHECK (client_type IN ('one-off', 'recurring'));
  END IF;
END $$;

-- Force schema cache refresh so the new column is immediately visible.
-- PostgREST caches the schema; without this, you may see
-- "Could not find the 'client_type' column" errors.
NOTIFY pgrst, 'reload schema';

-- Verification: query the column to confirm it exists in the schema cache
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type';

SELECT * FROM public.clients LIMIT 0;

-- =============================================
-- Business workflow preference (Step 2)
-- =============================================
-- Add business_workflow column if it doesn't already exist.
-- Default is 'both' so existing companies continue to work.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN business_workflow text NOT NULL DEFAULT 'both'
      CHECK (business_workflow IN ('single', 'returning', 'both'));
  END IF;
END $$;

-- Force Supabase schema cache refresh so the new column is immediately visible.
-- Without this, the PostgREST API will return:
--   "Could not find the 'business_workflow' column"
-- This NOTIFY command invalidates the schema cache across all connections.
NOTIFY pgrst, 'reload schema';

-- Verification: confirm the column now exists and is visible in the schema cache.
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow';

-- Trigger a schema cache refresh by selecting from the table.
-- This ensures the column is recognized before any UPDATE/DELETE operations.
SELECT * FROM public.companies LIMIT 0;

-- =============================================
-- Admin claimed guard (registration enforcement)
-- =============================================
-- Track whether the first admin has registered.  Uses the existing
-- `settings` table (key/value store) so no new table is needed.
-- The server queries this flag to decide whether to redirect visitors
-- to /register or show the normal login page.
--
-- Seed row (insert if missing):
INSERT INTO public.settings (key, value)
SELECT 'admin_claimed', 'false'
WHERE NOT EXISTS (SELECT 1 FROM public.settings WHERE key = 'admin_claimed');

-- =============================================
-- Activity log (Feature: Activity Log)
-- =============================================
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_log_company_id_idx on public.activity_log (company_id);
create index if not exists activity_log_created_at_idx on public.activity_log (created_at desc);
create index if not exists activity_log_action_idx on public.activity_log (action);
create index if not exists activity_log_entity_type_idx on public.activity_log (entity_type);

-- =============================================
-- Email templates (Feature: Email Templates)
-- =============================================
create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  subject text not null,
  body text not null,
  type text not null default 'custom',
  variables jsonb default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists email_templates_company_id_idx on public.email_templates (company_id);

-- =============================================
-- Currency support (Feature: Multi-Currency)
-- =============================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'currency'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN currency text NOT NULL DEFAULT 'USD';
  END IF;
END $$;

-- =============================================
-- SCHEMA VERIFICATION
-- Run these SELECT statements to confirm all
-- columns and tables exist and are visible.
-- =============================================

-- Verify company_components table exists
SELECT EXISTS (
  SELECT FROM information_schema.tables
  WHERE table_schema = 'public' AND table_name = 'company_components'
) AS company_components_exists;

-- Verify business_workflow column exists on companies
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
) AS business_workflow_column_exists;

-- Verify client_type column exists on clients
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
) AS client_type_column_exists;

-- Verify admin_claimed seed row exists
SELECT EXISTS (
  SELECT 1 FROM public.settings WHERE key = 'admin_claimed'
) AS admin_claimed_seed_exists;

-- Verify users_single_admin_idx exists
SELECT EXISTS (
  SELECT 1 FROM pg_indexes
  WHERE indexname = 'users_single_admin_idx'
) AS single_admin_index_exists;

-- Force schema cache refresh (run these separately if columns still missing):
--   NOTIFY pgrst, 'reload schema';
-- Or select from each table to trigger cache refresh:
--   SELECT * FROM public.companies LIMIT 0;
--   SELECT * FROM public.clients LIMIT 0;
--   SELECT * FROM public.company_components LIMIT 0;
