-- ===============================================================
-- CRM TEMPLATE — COMPLETE IDEMPOTENT MIGRATION
-- ===============================================================
-- Run this once in the Supabase SQL Editor against your project.
-- Safe to run multiple times; every statement uses IF NOT EXISTS
-- or equivalent guards.
--
-- INSTRUCTIONS:
--   1. Open https://supabase.com/dashboard/project/<ref>/sql/new
--   2. Paste this entire file
--   3. Click Run
--   4. Verify output with the verification SELECTs at the bottom
--   5. If columns still invisible, run:
--         NOTIFY pgrst, 'reload schema';
--      or simply:
--         SELECT * FROM public.companies LIMIT 0;
--         SELECT * FROM public.clients LIMIT 0;
-- ===============================================================

-- ===============================================================
-- 1. SETTINGS TABLE (key/value store)
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Seed admin_claimed row if missing
INSERT INTO public.settings (key, value)
SELECT 'admin_claimed', 'false'
WHERE NOT EXISTS (SELECT 1 FROM public.settings WHERE key = 'admin_claimed');

-- ===============================================================
-- 2. CLIENTS TABLE (with client_type column)
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.clients (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  phone        TEXT DEFAULT '',
  email        TEXT DEFAULT '',
  address      TEXT DEFAULT '',
  status       TEXT DEFAULT 'Lead',
  total_due    NUMERIC DEFAULT 0,
  amount_paid  NUMERIC DEFAULT 0,
  balance      NUMERIC DEFAULT 0,
  scope_of_work TEXT DEFAULT '',
  job_cost     NUMERIC DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add client_type column (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
  ) THEN
    ALTER TABLE public.clients ADD COLUMN client_type TEXT NOT NULL DEFAULT 'one-off'
      CHECK (client_type IN ('one-off', 'recurring'));
  END IF;
END $$;

-- ===============================================================
-- 3. PAYMENTS TABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.payments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id    BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
  amount       NUMERIC NOT NULL DEFAULT 0,
  payment_date TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===============================================================
-- 4. NOTES TABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.notes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id  BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===============================================================
-- 5. FINANCE OVERRIDES TABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.finance_overrides (
  year            INT PRIMARY KEY,
  total_expected  NUMERIC DEFAULT 0,
  total_received  NUMERIC DEFAULT 0,
  total_remaining NUMERIC DEFAULT 0,
  total_clients   INT DEFAULT 0,
  notes           TEXT,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===============================================================
-- 6. JOBS TABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.jobs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id    BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
  title        TEXT DEFAULT 'New Job',
  status       TEXT DEFAULT 'Prospect',
  scope_of_work TEXT DEFAULT '',
  total_due    NUMERIC DEFAULT 0,
  amount_paid  NUMERIC DEFAULT 0,
  balance      NUMERIC DEFAULT 0,
  job_cost     NUMERIC DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS jobs_client_id_idx    ON public.jobs (client_id);
CREATE INDEX IF NOT EXISTS jobs_created_at_idx   ON public.jobs (created_at DESC);

-- ===============================================================
-- 7. FINANCE MARGIN ENTRIES TABLE
-- ===============================================================
CREATE TABLE IF NOT EXISTS public.finance_margin_entries (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  client_name     TEXT DEFAULT '',
  category        TEXT DEFAULT 'Misc',
  project         TEXT DEFAULT '',
  invoice_status  TEXT DEFAULT 'Pending',
  amount          NUMERIC DEFAULT 0,
  expense_type    TEXT DEFAULT 'one-time',
  recurring       BOOLEAN DEFAULT FALSE,
  expense_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes           TEXT DEFAULT '',
  attachment_url  TEXT DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===============================================================
-- 8. INDEXES
-- ===============================================================
CREATE INDEX IF NOT EXISTS clients_created_at_idx              ON public.clients (created_at DESC);
CREATE INDEX IF NOT EXISTS payments_client_id_idx              ON public.payments (client_id);
CREATE INDEX IF NOT EXISTS payments_payment_date_idx           ON public.payments (payment_date DESC);
CREATE INDEX IF NOT EXISTS notes_client_id_idx                 ON public.notes (client_id);
CREATE INDEX IF NOT EXISTS notes_created_at_idx                ON public.notes (created_at DESC);
CREATE INDEX IF NOT EXISTS finance_margin_entries_client_id_idx ON public.finance_margin_entries (client_id);
CREATE INDEX IF NOT EXISTS finance_margin_entries_expense_date_idx ON public.finance_margin_entries (expense_date DESC);
CREATE INDEX IF NOT EXISTS finance_margin_entries_category_idx  ON public.finance_margin_entries (category);

-- ===============================================================
-- 9. MULTI-TENANT SYSTEM TABLES
-- ===============================================================

-- 9a. COMPANIES (with business_workflow column)
CREATE TABLE IF NOT EXISTS public.companies (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                  TEXT NOT NULL,
  slug                  TEXT UNIQUE NOT NULL,
  tagline               TEXT NOT NULL DEFAULT '',
  description           TEXT NOT NULL DEFAULT '',
  contact_email         TEXT NOT NULL DEFAULT '',
  logo_url              TEXT NOT NULL DEFAULT '',
  brand_primary_color   TEXT NOT NULL DEFAULT '#2563eb',
  brand_secondary_color TEXT NOT NULL DEFAULT '#7c3aed',
  onboarding_step       INT NOT NULL DEFAULT 1,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add business_workflow column (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN business_workflow TEXT NOT NULL DEFAULT 'both'
      CHECK (business_workflow IN ('single', 'returning', 'both'));
  END IF;
END $$;

-- Add currency column (idempotent — for multi-currency feature)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'currency'
  ) THEN
    ALTER TABLE public.companies ADD COLUMN currency TEXT NOT NULL DEFAULT 'USD';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS companies_slug_idx ON public.companies (slug);

-- 9b. USERS
CREATE TABLE IF NOT EXISTS public.users (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email               TEXT UNIQUE NOT NULL,
  password_hash       TEXT NOT NULL,
  display_name        TEXT NOT NULL DEFAULT '',
  role                TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  company_id          UUID REFERENCES public.companies(id) ON DELETE SET NULL,
  onboarding_complete BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS users_email_idx      ON public.users (email);
CREATE INDEX IF NOT EXISTS users_company_id_idx  ON public.users (company_id);

-- Prevent a second admin (unique partial index)
CREATE UNIQUE INDEX IF NOT EXISTS users_single_admin_idx
  ON public.users ((TRUE)) WHERE role = 'admin';

-- 9c. COMPANY COMPONENTS (Step 3 feature selection)
CREATE TABLE IF NOT EXISTS public.company_components (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  component_type  TEXT NOT NULL,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  display_order   INT NOT NULL DEFAULT 0,
  config          JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS company_components_company_id_idx      ON public.company_components (company_id);
CREATE INDEX IF NOT EXISTS company_components_company_order_idx   ON public.company_components (company_id, display_order);
CREATE UNIQUE INDEX IF NOT EXISTS company_components_unique_type_per_company
  ON public.company_components (company_id, component_type);

-- 9d. ACTIVITY LOG
CREATE TABLE IF NOT EXISTS public.activity_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES public.users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  entity_type TEXT,
  entity_id   TEXT,
  details     JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_log_company_id_idx  ON public.activity_log (company_id);
CREATE INDEX IF NOT EXISTS activity_log_created_at_idx  ON public.activity_log (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_log_action_idx      ON public.activity_log (action);
CREATE INDEX IF NOT EXISTS activity_log_entity_type_idx ON public.activity_log (entity_type);

-- 9e. EMAIL TEMPLATES
CREATE TABLE IF NOT EXISTS public.email_templates (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  subject     TEXT NOT NULL,
  body        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'custom',
  variables   JSONB DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS email_templates_company_id_idx ON public.email_templates (company_id);

-- ===============================================================
-- 10. SCHEMA CACHE VERIFICATION
-- Run these SELECT statements to confirm all objects exist.
-- ===============================================================

-- Verify business_workflow column exists
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'business_workflow'
) AS business_workflow_column_exists;

-- Verify client_type column exists
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'clients' AND column_name = 'client_type'
) AS client_type_column_exists;

-- Verify currency column exists
SELECT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'companies' AND column_name = 'currency'
) AS currency_column_exists;

-- Verify company_components table exists
SELECT EXISTS (
  SELECT FROM information_schema.tables
  WHERE table_schema = 'public' AND table_name = 'company_components'
) AS company_components_exists;

-- Verify admin_claimed seed row
SELECT EXISTS (
  SELECT 1 FROM public.settings WHERE key = 'admin_claimed'
) AS admin_claimed_seed_exists;

-- Verify users_single_admin_idx exists
SELECT EXISTS (
  SELECT 1 FROM pg_indexes
  WHERE indexname = 'users_single_admin_idx'
) AS single_admin_index_exists;

-- ===============================================================
-- 11. FORCE SCHEMA CACHE REFRESH (PostgREST)
-- Uncomment and run these if the schema cache still hasn't picked
-- up the new columns despite the verification queries above:
--
-- NOTIFY pgrst, 'reload schema';
--
-- Or force a cache refresh by selecting from each table:
-- SELECT * FROM public.companies LIMIT 0;
-- SELECT * FROM public.clients LIMIT 0;
-- SELECT * FROM public.company_components LIMIT 0;
-- ===============================================================
